trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DevPrac\gitwebapp.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    vsVersion: '17.0'
    platform: 'Any CPU'
    configuration: 'Release'